# -*- coding: utf-8 -*-
"""chatbot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tqsODR7CyzIqLrX_DuorhXfVFfhMv6CY
"""

pip install nltk

pip install newspaper3K

from newspaper import Article

import random
import string

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics.pairwise import cosine_similarity

import nltk
import warnings

warnings.filterwarnings('ignore')

nltk.download(('punkt'),quiet=True)

nltk.download('wordnet',quiet=True)

article=Article("https://www.cricbuzz.com/profiles/36/adam-gilchrist")

article.download()
article.parse()

article.nlp

corpus=article.text

text=corpus
#print(text)

sent_token=nltk.sent_tokenize(text)

#print(sent_token)

remove_pun = dict((ord(char), None) for char in string.punctuation)

print(string.punctuation)
print(remove_pun)

def LemNormalize(text):
  return nltk.word_tokenize(text.lower().translate(remove_pun))

greeting_input=["hi","hello","hola","hey","wassup"]
greeting_output=['howdy','hi','hey','hey there','hello']

def greeting(sentence):
  for word in sentence.split():
    if word.lower() in greeting_input:
      return random.choice(greeting_output)

def response (user_response):
  user_response=user_response.lower()
  robo=""
  sent_token.append(user_response)
  tfidfvec=TfidfVectorizer(tokenizer=LemNormalize,stop_words='english')
  tfidf=tfidfvec.fit_transform(sent_token)
  #print(tfidf)
  vals=cosine_similarity(tfidf[-1],tfidf)
  idx=vals.argsort()[0][-2]
  flat=vals.flatten()
  flat.sort()
  score=flat[-2]
  if(score==0):
    robo=robo+"I aplozise i could not understand"
  else:
    robo=robo+sent_token[idx]
  sent_token.remove(user_response)
  return robo

flag =True
print("CricBot:Hi i am cric bot how can i help you")
while(flag==True):
  user_response=input()
  user_response=user_response.lower()
  if(user_response=='bye'):
    flag=False
    print("CricBot:bye")
  else:
    if(greeting(user_response)!=None):
      print("CricBot:"+greeting(user_response))
    else:
      print("CricBot:"+response(user_response))

